/**
 * AccessToken helpers — ERC20 soulbound (1 token = access), shieldable via STRK20
 * Minimal JS wrapper around AccessToken + AccessFactory contracts.
 * Follows same RpcProvider pattern as lib/filevault.js
 */

import { Contract } from 'starknet'
import { config } from '../sdk/core/config'
import { getReadProvider } from '../sdk/core/provider'

// Try to load compiled ABIs (generated by contracts build); fallback to minimal inline ABI if missing
const AccessTokenABI = [
  { type: 'function', name: 'name', inputs: [], outputs: [{ type: 'core::byte_array::ByteArray' }], state_mutability: 'view' },
  { type: 'function', name: 'symbol', inputs: [], outputs: [{ type: 'core::byte_array::ByteArray' }], state_mutability: 'view' },
  { type: 'function', name: 'decimals', inputs: [], outputs: [{ type: 'core::integer::u8' }], state_mutability: 'view' },
  { type: 'function', name: 'total_supply', inputs: [], outputs: [{ type: 'core::integer::u256' }], state_mutability: 'view' },
  { type: 'function', name: 'balance_of', inputs: [{ name: 'account', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [{ type: 'core::integer::u256' }], state_mutability: 'view' },
  { type: 'function', name: 'get_price', inputs: [], outputs: [{ type: 'core::integer::u256' }], state_mutability: 'view' },
  { type: 'function', name: 'get_duration', inputs: [], outputs: [{ type: 'core::integer::u64' }], state_mutability: 'view' },
  { type: 'function', name: 'get_expiry', inputs: [{ name: 'account', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [{ type: 'core::integer::u64' }], state_mutability: 'view' },
  { type: 'function', name: 'has_access', inputs: [{ name: 'account', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [{ type: 'core::bool' }], state_mutability: 'view' },
  { type: 'function', name: 'is_expired', inputs: [{ name: 'account', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [{ type: 'core::bool' }], state_mutability: 'view' },
  { type: 'function', name: 'get_owner', inputs: [], outputs: [{ type: 'core::starknet::contract_address::ContractAddress' }], state_mutability: 'view' },
  { type: 'function', name: 'mint', inputs: [], outputs: [], state_mutability: 'external' },
  { type: 'function', name: 'mint_to', inputs: [{ name: 'recipient', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [], state_mutability: 'external' },
]
const AccessFactoryABI = [
  { type: 'function', name: 'create_token', inputs: [{ name: 'name', type: 'core::byte_array::ByteArray' }, { name: 'symbol', type: 'core::byte_array::ByteArray' }, { name: 'price', type: 'core::integer::u256' }, { name: 'duration', type: 'core::integer::u64' }], outputs: [{ type: 'core::starknet::contract_address::ContractAddress' }], state_mutability: 'external' },
  { type: 'function', name: 'get_token_count', inputs: [], outputs: [{ type: 'core::integer::u64' }], state_mutability: 'view' },
  { type: 'function', name: 'get_token', inputs: [{ name: 'index', type: 'core::integer::u64' }], outputs: [{ type: 'core::starknet::contract_address::ContractAddress' }], state_mutability: 'view' },
  { type: 'function', name: 'get_seller_token_count', inputs: [{ name: 'seller', type: 'core::starknet::contract_address::ContractAddress' }], outputs: [{ type: 'core::integer::u64' }], state_mutability: 'view' },
  { type: 'function', name: 'get_seller_token', inputs: [{ name: 'seller', type: 'core::starknet::contract_address::ContractAddress' }, { name: 'index', type: 'core::integer::u64' }], outputs: [{ type: 'core::starknet::contract_address::ContractAddress' }], state_mutability: 'view' },
]

const FACTORY_ADDRESS = config.accessFactoryAddress
const readProvider = getReadProvider()

function toBigIntU256(val) {
  if (!val) return 0n
  if (typeof val === 'bigint') return val
  if (typeof val === 'object' && val.low !== undefined) {
    return BigInt(val.low) + (BigInt(val.high) << 128n)
  }
  try { return BigInt(val) } catch { return 0n }
}

function normalizeAddress(addr) {
  if (!addr || addr === '0x0' || addr === 0) return '0x0'
  // If it's already a hex string with 0x prefix, return as-is
  if (typeof addr === 'string' && addr.startsWith('0x')) return addr
  // Convert felt252 (decimal number or BigInt) to 0x hex
  try {
    const bi = typeof addr === 'bigint' ? addr : BigInt(addr)
    if (bi === 0n) return '0x0'
    return '0x' + bi.toString(16)
  } catch {}
  return String(addr)
}

export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000000000000000000000000000'

export function isZeroAddress(addr) {
  if (!addr) return true
  const s = String(addr).toLowerCase()
  if (s === '0x0' || s === ZERO_ADDRESS.toLowerCase()) return true
  try { return BigInt(s) === 0n } catch { return false }
}

/**
 * Get AccessToken info (name, symbol, price, duration, owner, supply)
 * @param {string} tokenAddress - AccessToken contract address
 * @returns {Promise<Object|null>} { name, symbol, price (bigint), priceFormatted, duration, durationLabel, owner, totalSupply }
 */
export async function getTokenInfo(tokenAddress) {
  if (!tokenAddress || isZeroAddress(tokenAddress)) return null
  try {
    const contract = new Contract({ abi: AccessTokenABI, address: tokenAddress, providerOrAccount: readProvider })

    // Decode ByteArray from starknet.js response
    // ByteArray = { data: felt252[], pending_word: felt252, pending_word_length: u32 }
    const decodeByteArray = (raw) => {
      if (!raw) return ''
      // Already a plain string
      if (typeof raw === 'string' && !raw.match(/^[0-9a-fx]+$/i)) return raw
      // Object with data/pending_word — ByteArray struct
      if (typeof raw === 'object' && raw !== null && !Array.isArray(raw)) {
        const words = raw.data || []
        const pending = raw.pending_word
        const pendingLen = raw.pending_word_length || 0
        let bytes = []
        for (const w of words) {
          const bi = BigInt(w)
          const hex = bi.toString(16).padStart(64, '0')
          for (let i = 0; i < hex.length; i += 2) {
            const b = parseInt(hex.slice(i, i + 2), 16)
            if (b) bytes.push(b)
          }
        }
        if (pending && pendingLen > 0) {
          const bi = BigInt(pending)
          const hex = bi.toString(16).padStart(64, '0')
          for (let i = 0; i < pendingLen * 2; i += 2) {
            const b = parseInt(hex.slice(i, i + 2), 16)
            if (b) bytes.push(b)
          }
        }
        return String.fromCharCode(...bytes)
      }
      // Array of felts — try each as felt252 short string
      if (Array.isArray(raw)) {
        for (const item of raw) {
          const s = decodeByteArray(item)
          if (s && s.trim()) return s
        }
        return ''
      }
      // Single felt252 — decode as short string
      try {
        const bi = BigInt(raw)
        const hex = bi.toString(16).padStart(64, '0')
        let str = ''
        for (let i = 0; i < hex.length; i += 2) {
          const b = parseInt(hex.slice(i, i + 2), 16)
          if (b) str += String.fromCharCode(b)
        }
        return str.replace(/^\0+/, '').trim()
      } catch {}
      return String(raw || '')
    }

    // Use provider.callContract directly — starknet.js Contract abstraction doesn't decode ByteArray reliably
    const rawCall = async (entrypoint, args = []) => {
      try {
        const res = await readProvider.callContract({
          contractAddress: tokenAddress,
          entrypoint,
          calldata: args,
        })
        return res?.result || res || []
      } catch (e) {
        console.warn(`[getTokenInfo] ${entrypoint} call failed:`, e.message)
        return []
      }
    }

    // Decode ByteArray from raw felt array: [data_len, ...data_felts, pending_word, pending_word_length]
    const decodeByteArrayFromFelts = (felts) => {
      if (!felts || !Array.isArray(felts) || felts.length === 0) return ''
      const dataLen = Number(felts[0] || 0)
      let bytes = []
      for (let i = 1; i <= dataLen && i < felts.length; i++) {
        const bi = BigInt(felts[i])
        const hex = bi.toString(16).padStart(64, '0')
        for (let j = 0; j < 64; j += 2) {
          const b = parseInt(hex.slice(j, j + 2), 16)
          if (b) bytes.push(b)
        }
      }
      if (bytes.length > 0) return String.fromCharCode(...bytes)
      // Fallback: try first felt as short string
      try {
        const bi = BigInt(felts[0])
        const hex = bi.toString(16).padStart(64, '0')
        let str = ''
        for (let j = 0; j < 64; j += 2) {
          const b = parseInt(hex.slice(j, j + 2), 16)
          if (b) str += String.fromCharCode(b)
        }
        return str.replace(/^\0+/, '').trim()
      } catch {}
      return ''
    }

    const nameResult = await rawCall('name')
    const symbolResult = await rawCall('symbol')
    const name = decodeByteArrayFromFelts(nameResult)
    const symbol = decodeByteArrayFromFelts(symbolResult)
    console.log('[getTokenInfo] name raw:', nameResult, '→', name, '| symbol raw:', symbolResult, '→', symbol)

    const priceResult = await rawCall('get_price')
    const price = toBigIntU256(priceResult?.[0] || 0n)
    const durResult = await rawCall('get_duration')
    const duration = Number(durResult?.[0] || 0)
    const supplyResult = await rawCall('total_supply')
    const supply = toBigIntU256(supplyResult)
    const ownerResult = await rawCall('get_owner')
    const owner = normalizeAddress(ownerResult?.[0] || '0x0')
    const priceFormatted = price === 0n ? 'Free' : (Number(price) / 1e18).toFixed(4) + ' STRK'
    let durationLabel = 'Forever'
    if (duration !== 0) {
      const days = Math.round(duration / 86400)
      if (days >= 365) durationLabel = `${Math.round(days/30)}M`
      else if (days >= 30) durationLabel = `${Math.round(days/30)} months`
      else durationLabel = `${days}d`
    }
    return { address: tokenAddress, name: String(name), symbol: String(symbol), price, priceFormatted, duration, durationLabel, totalSupply: supply, owner: normalizeAddress(owner) }
  } catch (e) {
    console.warn('[getTokenInfo] failed for', tokenAddress, e.message)
    return null
  }
}

/**
 * Check has_access via balance>0 && !is_expired (public balance)
 * @param {string} tokenAddress
 * @param {string} accountAddress
 * @returns {Promise<{hasAccess: boolean, isExpired: boolean, expiry: bigint, balance: bigint}>}
 */
export async function checkAccess(tokenAddress, accountAddress) {
  if (!tokenAddress || isZeroAddress(tokenAddress)) return { hasAccess: true, isExpired: false, expiry: 0n, balance: 0n, isPublic: true }
  if (!accountAddress) return { hasAccess: false, isExpired: true, expiry: 0n, balance: 0n, isPublic: false }
  try {
    const contract = new Contract({ abi: AccessTokenABI, address: tokenAddress, providerOrAccount: readProvider })
    const callOrMethod = (name, args) => {
      if (typeof contract[name] === 'function') return contract[name](...args)
      return contract.call(name, args)
    }
    const [hasAccessRaw, isExpiredRaw, expiryRaw, balRaw] = await Promise.all([
      callOrMethod('has_access', [accountAddress]).catch(() => false),
      callOrMethod('is_expired', [accountAddress]).catch(() => true),
      callOrMethod('get_expiry', [accountAddress]).catch(() => 0),
      callOrMethod('balance_of', [accountAddress]).catch(() => 0n),
    ])
    const hasAccess = Boolean(hasAccessRaw === true || hasAccessRaw === 1 || String(hasAccessRaw) === 'true')
    const isExpired = Boolean(isExpiredRaw === true || isExpiredRaw === 1 || String(isExpiredRaw) === 'true')
    const expiry = BigInt(expiryRaw || 0)
    const balance = toBigIntU256(balRaw)
    // has_access per spec: balance>0 && !is_expired — double-check
    const computed = balance > 0n && !isExpired
    return { hasAccess: computed && hasAccess, isExpired, expiry, balance, isPublic: false }
  } catch (e) {
    console.warn('[checkAccess] failed', e.message)
    return { hasAccess: false, isExpired: true, expiry: 0n, balance: 0n, isPublic: false, error: e.message }
  }
}

/**
 * Reveal shielded balance for AccessToken (STRK20). Requires wallet account with strk20Balances.
 * @param {Object} account - WalletAccountV6 instance
 * @param {string} tokenAddress - AccessToken address
 * @returns {Promise<{shieldedBalance: bigint, hasShieldedAccess: boolean, error?: string}>}
 */
export async function revealShieldedAccess(account, tokenAddress) {
  if (!account || !tokenAddress || isZeroAddress(tokenAddress)) return { shieldedBalance: 0n, hasShieldedAccess: false }
  try {
    if (typeof account.strk20Balances !== 'function') {
      return { shieldedBalance: 0n, hasShieldedAccess: false, error: 'Wallet does not support STRK20' }
    }
    const balances = await account.strk20Balances([tokenAddress])
    const entry = balances?.find(b => String(b.token || b.address || '').toLowerCase() === tokenAddress.toLowerCase()) || balances?.[0]
    const raw = entry?.balance ?? entry?.amount ?? '0x0'
    const bal = toBigIntU256(raw)
    return { shieldedBalance: bal, hasShieldedAccess: bal > 0n }
  } catch (e) {
    console.warn('[revealShieldedAccess] failed', e.message)
    return { shieldedBalance: 0n, hasShieldedAccess: false, error: e.message }
  }
}

/**
 * Mint AccessToken to caller (has_access check via balance). Handles free vs paid metadata (payment off-chain via STRK20 private transfer if needed).
 * @param {Object} account - WalletAccountV6 instance
 * @param {string} tokenAddress
 * @returns {Promise<Object>} tx result
 */
export async function mintAccess(account, tokenAddress) {
  if (!account) throw new Error('Wallet not connected')
  if (!tokenAddress || isZeroAddress(tokenAddress)) throw new Error('Invalid token address')
  const contract = new Contract({ abi: AccessTokenABI, address: tokenAddress, providerOrAccount: account })
  try {
    const result = await (contract.mint ? contract.mint() : contract.call('mint', []))
    return result
  } catch (e) {
    // fallback via direct execute
    const res = await account.execute({ contractAddress: tokenAddress, entrypoint: 'mint', calldata: [] })
    return res
  }
}

/**
 * Mint (airdrop) to specific recipient — only owner can call.
 * @param {Object} account - WalletAccountV6 (must be token owner)
 * @param {string} tokenAddress
 * @param {string} recipient
 */
export async function mintTo(account, tokenAddress, recipient) {
  if (!account) throw new Error('Wallet not connected')
  if (!tokenAddress || isZeroAddress(tokenAddress)) throw new Error('Invalid token address')
  const contract = new Contract({ abi: AccessTokenABI, address: tokenAddress, providerOrAccount: account })
  try {
    const result = await (contract.mint_to ? contract.mint_to(recipient) : contract.call('mint_to', [recipient]))
    return result
  } catch (e) {
    const res = await account.execute({ contractAddress: tokenAddress, entrypoint: 'mint_to', calldata: [recipient] })
    return res
  }
}

/**
 * Create a new AccessToken via Factory (seller creates N tokens). Uses factory create_token.
 * @param {Object} account - WalletAccountV6
 * @param {Object} params - { name: string, symbol: string, price: bigint|string, duration: number }
 * @returns {Promise<{tokenAddress: string, txHash?: string}>}
 */
export async function createAccessToken(account, { name, symbol, price = 0, duration = 0 }) {
  if (!account) throw new Error('Wallet not connected')
  if (!FACTORY_ADDRESS) throw new Error('NEXT_PUBLIC_ACCESS_FACTORY_ADDRESS not set — deploy AccessFactory first')
  if (!name || !symbol) throw new Error('name and symbol required')
  const priceBig = BigInt(price)
  const priceU256 = { low: priceBig & ((1n << 128n) - 1n), high: priceBig >> 128n }
  const factory = new Contract({ abi: AccessFactoryABI, address: FACTORY_ADDRESS, providerOrAccount: account })
  try {
    // Use callData.compile which correctly handles ByteArray and u256 for this contract
    const calldata = factory.callData.compile('create_token', [name, symbol, priceU256, duration])
    const res = await account.execute({
      contractAddress: FACTORY_ADDRESS,
      entrypoint: 'create_token',
      calldata: calldata,
    })
    return { tokenAddress: null, result: res }
  } catch (e) {
    console.warn('[createAccessToken] callData.compile failed, trying direct', e.message, e)
    try {
      const result = await (factory.create_token 
        ? factory.create_token(name, symbol, priceU256, duration) 
        : factory.call('create_token', [name, symbol, priceU256, duration]))
      return { tokenAddress: null, result }
    } catch (e2) {
      console.warn('[createAccessToken] direct also failed', e2.message)
      throw e2
    }
  }
}

/**
 * List tokens owned by seller via Factory enumeration.
 * @param {string} sellerAddress
 * @returns {Promise<string[]>} array of token addresses
 */
export async function getSellerTokens(sellerAddress) {
  if (!FACTORY_ADDRESS) return []
  if (!sellerAddress) return []
  try {
    const factory = new Contract({ abi: AccessFactoryABI, address: FACTORY_ADDRESS, providerOrAccount: readProvider })
    const callOrMethod = (name, args) => typeof factory[name] === 'function' ? factory[name](...args) : factory.call(name, args)
    const countRaw = await callOrMethod('get_seller_token_count', [sellerAddress]).catch(() => 0)
    const count = Number(countRaw || 0)
    if (count === 0) return []
    const tokens = []
    for (let i = 0; i < count; i++) {
      try {
        const addr = await callOrMethod('get_seller_token', [sellerAddress, i])
        if (addr && !isZeroAddress(addr)) tokens.push(normalizeAddress(addr))
      } catch {}
    }
    return tokens
  } catch (e) {
    console.warn('[getSellerTokens] failed', e.message)
    return []
  }
}

/**
 * List all factory tokens (global)
 */
export async function getAllFactoryTokens() {
  if (!FACTORY_ADDRESS) return []
  try {
    const factory = new Contract({ abi: AccessFactoryABI, address: FACTORY_ADDRESS, providerOrAccount: readProvider })
    const callOrMethod = (name, args) => typeof factory[name] === 'function' ? factory[name](...args) : factory.call(name, args)
    const countRaw = await callOrMethod('get_token_count', []).catch(() => 0)
    const count = Number(countRaw || 0)
    const tokens = []
    for (let i = 0; i < Math.min(count, 50); i++) {
      try {
        const addr = await callOrMethod('get_token', [i])
        if (addr && !isZeroAddress(addr)) tokens.push(normalizeAddress(addr))
      } catch {}
    }
    return tokens
  } catch {
    return []
  }
}

/**
 * Helper: format expiry timestamp to readable date, or 'Forever' if 0
 */
export function formatExpiry(expiry) {
  const ts = Number(expiry || 0)
  if (ts === 0) return 'Forever'
  const d = new Date(ts * 1000)
  return d.toLocaleDateString() + ' ' + d.toLocaleTimeString()
}

/**
 * Tot price × months helper for SellFlow dropdown (live calculation)
 * @param {bigint} pricePerDuration - token price (wei)
 * @param {number} months - e.g., 1, 3, 12
 * @returns {string} formatted total
 */
export function calcTotalPrice(pricePerDuration, months) {
  const price = BigInt(pricePerDuration || 0)
  if (price === 0n) return 'Free'
  const total = price * BigInt(months)
  return (Number(total) / 1e18).toFixed(4) + ' STRK'
}
