[package]
name = "ownerz_filevault"
version = "0.1.0"
cairo-version = "2.18.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"
openzeppelin_token = "3.0.0"
key_onchain = { path = "../lib/key-onchain" }

[dev-dependencies]
snforge_std = "0.61.0"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
